<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "danceclub"
 *
 * Auto generated by Extension Builder 2016-03-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Tango Club',
	'description' => 'Book partner dance classes or simply check for updates on events. It\'s a small management tool for Dance Schools.',
	'category' => 'misc',
	'author' => 'Samuel Scherer',
	'author_email' => 'trashcash@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);